[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "chromium",
  "chromedriver"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "python simple_app.py"

[variables]
PYTHONPATH = "/app"
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"