[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "chromium",
  "chromedriver"
]

[phases.install]
cmds = [
  "pip install --user --upgrade pip setuptools wheel",
  "pip install --user -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[phases.start]
cmds = [
  "python simple_app.py"
]

[start]
cmd = "python simple_app.py"

[variables]
PYTHONPATH = "/app"
CHROME_BIN = "$(which chromium)"
CHROMEDRIVER_PATH = "$(which chromedriver)"
