[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.venv",
  "chromium",
  "chromedriver"
]

[phases.install]
cmds = [
  "python -m venv /app/venv",
  ". /app/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /app/venv/bin/activate",
  "echo 'Build phase completed'"
]

[phases.start]
cmds = [
  ". /app/venv/bin/activate",
  "python simple_app.py"
]

[start]
cmd = "python simple_app.py"

[variables]
PYTHONPATH = "/app"
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"
