[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.virtualenv",
  "chromium",
  "chromedriver"
]

[phases.install]
cmds = [
  "python -m pip install --user --upgrade pip",
  "python -m pip install --user virtualenv",
  "python -m virtualenv /app/venv",
  "/app/venv/bin/pip install --upgrade pip setuptools wheel",
  "/app/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[phases.start]
cmds = [
  "/app/venv/bin/python simple_app.py"
]

[start]
cmd = "/app/venv/bin/python simple_app.py"

[variables]
PYTHONPATH = "/app"
CHROME_BIN = "$(which chromium)"
CHROMEDRIVER_PATH = "$(which chromedriver)"
